import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ArticleLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-4/5 md:w-3/5 py-12 min-h-screen mx-auto animate-fade animate-duration-200">
      {children}
    </div>
  );
}
